services:
  api:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1qa2ws3ed
      - DB_NAME=test_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1qa2ws3ed
      - MYSQL_DATABASE=test_db
    ports:
      - "3308:3306"

    volumes:
      - db-data:/var/lib/mysql
      - ./V001__init.sql:/docker-entrypoint-initdb.d/V001__init.sql:ro

volumes:
  db-data: